<?xml version='1.1' encoding='UTF-8'?>
<!DOCTYPE tkrInternalAlignment [
<!--
   $Header: /nfs/slac/g/glast/ground/cvs/calibUtil/xml/Tkr/sampleIntratowerAlign.xml,v 1.1 2008/05/07 22:33:07 jrb Exp $

   /**  @file       tkrAlign.dtd
        @authors    J. Bogart

        dtd for tracker inter-tower and intra-tower alignment constants

    */
-->
<!--
    form of alignment constants is the same for several components 
           disp: x, y and z displacements; defaults to all 0
           rot:  rotations about x, y and z, applied in that order.
                 defaults to all 0
-->
<!ELEMENT tkrTowerAlignment (generic, tower*) >

<!ELEMENT generic EMPTY >
<!ATTLIST generic 
   instrument  NMTOKEN #REQUIRED
   timestamp   NMTOKEN #IMPLIED
   runId       NMTOKEN #IMPLIED
   calType     NMTOKEN #IMPLIED
   DTDVersion  NMTOKEN "v1r0"
   fmtVersion  NMTOKEN #IMPLIED
   creatorName NMTOKEN #IMPLIED
   creatorVersion NMTOKEN #IMPLIED
 >

<!ELEMENT tower EMPTY>
<!ATTLIST tower id NMTOKEN #REQUIRED
               disp NMTOKENS "0.0 0.0 0.0" rot NMTOKENS "0.0 0.0 0.0"
>

<!ELEMENT tkrInternalAlignment (generic, towerInternal*)>

<!ELEMENT towerInternal (tray*) >
<!ATTLIST towerInternal id NMTOKEN #REQUIRED>

<!ELEMENT tray (face*) >
<!ATTLIST tray id NMTOKEN #REQUIRED
                disp NMTOKENS "0.0 0.0 0.0" rot NMTOKENS "0.0 0.0 0.0"
>

<!ELEMENT face (ladder*) >
<!ATTLIST face id NMTOKEN #REQUIRED
                disp NMTOKENS "0.0 0.0 0.0" rot NMTOKENS "0.0 0.0 0.0"
>

<!ELEMENT ladder (wafer*) >
<!ATTLIST ladder id NMTOKEN #REQUIRED
                disp NMTOKENS "0.0 0.0 0.0" rot NMTOKENS "0.0 0.0 0.0"
>

<!ELEMENT wafer EMPTY>
<!ATTLIST wafer id NMTOKEN #REQUIRED
                disp NMTOKENS "0.0 0.0 0.0" rot NMTOKENS "0.0 0.0 0.0"
>
]>
<tkrInternalAlignment>
  <generic        instrument="LAT" creatorName="Joanne" />
  <towerInternal id='1' >
    <tray id='3' />
    <tray id='5' >
      <face id="0" disp="1.1 2.1 3.1" />
      <face id="1" rot="1.2 2.1 3.3 " />
    </tray>
  </towerInternal >
  <towerInternal id='6'>
    <tray id="16">
      <face id="0" >
        <ladder id="1" disp="1.0 0.9 0.8" rot="0.0 2.0 0.0" >
          <wafer id="2" disp="2.0 2.1 2.2" rot="0.2 0.21 0.214" />
        </ladder>
      </face>
    </tray>
  </towerInternal>

</tkrInternalAlignment>
