<!--
   $Header: /nfs/slac/g/glast/ground/cvs/calibUtil/xml/Cal/SampleAsym.xml,v 1.1 2004/09/24 22:43:27 jrb Exp $

   /**  @file       SampleTholdMuon.xml
        @authors    J. Bogart

        Sample TholdMuon file.  

    */
-->

<!-- First define doctype and literally insert correct dtd -->
<!--
  Whatever creates this file should
   just insert the contents of calibUtil/xml/CalcalCalib_v2r2.dtd
   between the [    ]
-->

<!DOCTYPE calCalib [

<!ELEMENT calCalib (generic, dimension, dac*, xpos?, tower* ) >
       
<!-- Container for all the header/metadata type information to be
     included here.  Complete metadata will be found in the calibration
     MySQL database. 

     Description of attributes:

            instrument    - one of "flight", "EM", etc.  Could also
                            be implemented as enumeration rather than
                            NMTOKEN
            timestamp     - when the file was written (date and time)
            calType       - one of "TKRBadStrips", "CALLightAttenuation",
                            etc.
            formatVersion - sufficient versioning information so that
                            software attempting to read the file can
                            determine if it supports this version. 
                            [Might get rid of this here and just keep
                            it in the MySQL metadata table]
 -->
<!ELEMENT  generic  (inputSample?) >
<!ATTLIST generic  
   instrument  (LAT | BFEM | BTEM | EM | EM2 | CU) #REQUIRED
   timestamp   NMTOKEN #REQUIRED
   calibType (CAL_LightAtt | CAL_LightAsym | CAL_LightYield |
              CAL_Ped | CAL_ElecGain | CAL_IntNonlin | CAL_DiffNonlin |
              CAL_MuSlope | CAL_Asym | CAL_MevPerDac | CAL_TholdCI |
              CAL_TholdMuon)    #REQUIRED
   DTDVersion  NMTOKEN "v2r2"       
   fmtVersion  NMTOKEN #REQUIRED >

<!-- Description of events used as input to the procedure 
     Start- and stop-times should be timestamps of earliest and
     latest events included in sample.
     inputSample is (for now) optional.
-->
<!ELEMENT inputSample (#PCDATA) >
<!ATTLIST inputSample  startTime NMTOKEN #REQUIRED
                       stopTime  NMTOKEN #REQUIRED
                       triggers  NMTOKENS #REQUIRED 
                       source    NMTOKENS #REQUIRED
                       mode      NMTOKEN  #REQUIRED>

<!-- In many cases calibration is done per range: LEX8 is low-energy 
   (= large) diode, x8 amplification; LEX1 is low-energy, low amplification.
   Similarly have HEX8, HEX1 for high-energy (small) diode.
   Unfortunately can't use parameter entities since they aren't allowed
   when the dtd is literally included in an xml file, something
   we'd like to support.
  -->

<!-- For light asymmetry may lump together amplifications (and by
  definition one set of constants applies to both crystal ends, since
  constants quantify *asymmetry*), so have a set of constants per
  diode-type -->

<!-- Describe how the data is dimensioned:
        number of tower rows
        number of tower columns
        number of calorimeter layers
        number of crystals in a layer ("columns")
        number of faces      (mostly 2; 1 for light asymmetry data)
        number of ranges     (fixed at 4? for now just default to 4) 
        number of sets of dac settings (mostly 0)
        number of xpos elements.  Can only be 0 or 1
        exact    may be "true" or "false".  If "true", above information
                 may be mutliplied to compute total number of innermost
                 elements (e.g., calPed)

   Use the following conventions to determine which data element 
   corresponds to a particular physical crystal, optional face and
   gain range:
       * Tower number is computed from row and column as
                 tower = column + (nCol)*row
       * The data can be viewed as a 5-dimensional array where
         the indices from most- to least-significant are
              tower
              layer
              xtal   (often called "column" in calorimeter code)
              face
              range
         So the first two data elements will correspond to 
           (tower=0,layer=0, xtal=0, face=0, range=0)
           (tower=0,layer=0, xtal=0, face=0, range=1)
 
         The total number of data elements (for the default
         case, with exact = "true") is just
                nRow*nCol*nLayer*nXtal*nFace*nRange

 -->
<!ELEMENT dimension EMPTY>
<!ATTLIST dimension nRow NMTOKEN  #REQUIRED
                    nCol NMTOKEN  #REQUIRED
                    nLayer NMTOKEN #REQUIRED
                    nXtal  NMTOKEN #REQUIRED
                    nFace  NMTOKEN #REQUIRED
                    nRange NMTOKEN "4"      
                    nDacCol NMTOKEN "0" 
                    nXpos  (0 | 1) "0"
                    exact  (true | false) "true" >

<!-- For those calibrations involving setting a dac, keep track of
    settings.  Expect one set per range where used; else 0. Number 
    should match value of dimension attribute nDacCol  -->
<!ELEMENT dac EMPTY>
<!ATTLIST dac range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
          values NMTOKENS #REQUIRED
          error  NMTOKEN  #IMPLIED >   <!-- for now.  May want default -->

<!ELEMENT xpos EMPTY>
<!ATTLIST xpos values NMTOKENS #REQUIRED>

<!ELEMENT tower (layer*) >
<!ATTLIST tower iRow NMTOKEN #REQUIRED
                iCol NMTOKEN #REQUIRED >

<!ELEMENT layer (xtal*) >
<!ATTLIST layer iLayer NMTOKEN #REQUIRED>

<!ELEMENT xtal (face, face?) >
<!ATTLIST xtal iXtal NMTOKEN #REQUIRED>

<!-- each face has data for all four ranges, ordered by range number -->
<!ELEMENT face (calPed* | calGain* | muSlope* | lightAsym* | intNonlin*
                        | mevPerDac* | tholdCI* | tholdMuon*
                        | asym* ) >
<!ATTLIST face end (NEG | POS | NA) #REQUIRED >


<!ELEMENT calPed  EMPTY>
<!ATTLIST calPed  range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                  avg NMTOKEN #REQUIRED
                  sig NMTOKEN #REQUIRED
                  cos NMTOKEN "2" >

<!ELEMENT calGain EMPTY>
<!ATTLIST calGain range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                  avg NMTOKEN #REQUIRED
                  sig NMTOKEN #REQUIRED>

<!ELEMENT muSlope EMPTY>
<!ATTLIST muSlope range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                  slope NMTOKEN #REQUIRED
                  error NMTOKEN "0.0" >

<!ELEMENT lightAsym EMPTY>
<!ATTLIST lightAsym diode (LE | HE) #REQUIRED
                    values NMTOKENS #REQUIRED
                    error NMTOKEN #REQUIRED >

<!ELEMENT intNonlin EMPTY>
<!ATTLIST intNonlin range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                    values NMTOKENS #REQUIRED
                    error NMTOKEN   #REQUIRED >

<!-- Some of mevPerDac information is per-crystal, some is per face.  So
     <mevPerDac> is identified by tower/layer/crystal and contains two
     <bigSmall> elements for the per-face information. 
 -->
<!ELEMENT mevPerDac (bigSmall, bigSmall) >
<!ATTLIST mevPerDac bigVal NMTOKEN #REQUIRED
                    bigSig NMTOKEN #REQUIRED
                    smallVal NMTOKEN #REQUIRED
                    smallSig NMTOKEN #REQUIRED
>
<!ELEMENT bigSmall EMPTY>
<!ATTLIST bigSmall  end (NEG | POS) #REQUIRED
                    bigSmallRatioVals NMTOKENS #REQUIRED
                    bigSmallRatioSigs NMTOKENS #REQUIRED
>

<!ELEMENT asym EMPTY>
<!ATTLIST asym bigVals NMTOKENS #REQUIRED
               bigSigs NMTOKENS #REQUIRED
               smallVals  NMTOKENS #REQUIRED
               smallSigs  NMTOKENS #REQUIRED
               NsmallPbigVals NMTOKENS #REQUIRED
               NsmallPbigSigs NMTOKENS #REQUIRED
               PsmallNbigVals NMTOKENS #REQUIRED
               PsmallNbigSigs NMTOKENS #REQUIRED
>

<!-- Some of tholdCI information is per-crystal-face, some is per range.  So
     <tholdCI> is identified by tower/layer/crystal/face and contains up
       to 4 tholdCIRange elements for per-range information
 -->
<!ELEMENT tholdCI (tholdCIRange, tholdCIRange?, tholdCIRange?, tholdCIRange?) >
<!ATTLIST tholdCI FLEVal NMTOKEN #REQUIRED
                  FLESig NMTOKEN #REQUIRED
                  FHEVal NMTOKEN #REQUIRED
                  FHESig NMTOKEN #REQUIRED
                  LACVal NMTOKEN #REQUIRED
                  LACSig NMTOKEN #REQUIRED
>

<!ELEMENT tholdCIRange EMPTY>
<!ATTLIST tholdCIRange range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                       pedVal NMTOKEN #REQUIRED
                       pedSig NMTOKEN #REQUIRED
                       ULDVal NMTOKEN #REQUIRED
                       ULDSig NMTOKEN #REQUIRED
>

<!-- Some of tholdMuon information is per-crystal-face, some is per range.  So
     <tholdMuon> is identified by tower/layer/crystal/face and contains up
       to 4 tholdMuonRange elements for per-range information
 -->
<!ELEMENT tholdMuon (tholdMuonRange, tholdMuonRange?, tholdMuonRange?, 
                     tholdMuonRange?) >
<!ATTLIST tholdMuon FLEVal NMTOKEN #REQUIRED
                    FLESig NMTOKEN #REQUIRED
                    FHEVal NMTOKEN #REQUIRED
                    FHESig NMTOKEN #REQUIRED >

<!ELEMENT tholdMuonRange EMPTY>
<!ATTLIST tholdMuonRange range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                         pedVal NMTOKEN #REQUIRED
                         pedSig NMTOKEN #REQUIRED
>

] >

<!-- Now comes the calibration data --> 

<calCalib>
  <generic instrument="EM" timestamp="2003-9-2-12:56"
           calibType="CAL_TholdMuon" fmtVersion="v2r2">
<!--
    inputSample element is option; comment it out here
    <inputSample>
            Bunch of stuff
    </inputSample>
-->
  </generic>


  <!-- LAT instrument: 4x4 tower array, 8 layers, 12 columns.  
       Need not contain data for all towers.  If data is only partial, set
       exact="false"  -->
  <!-- For TholdMuon file,  nRange for this purpose is always 1.   The
       per-range information is kept in child elements. 
       There is no xpos data.
    -->
  <dimension nRow="1" nCol="1" nLayer="3" nXtal="2" nFace="2" nRange="1" />

  <tower iRow="0" iCol="0">
    <layer iLayer="0">
      <xtal iXtal="0">
        <face end="NEG">
          <tholdMuon FLEVal="8.0" FLESig="0.4" FHEVal="14.1" FHESig="0.8">
<!-- Just leave out unused range -->
            <tholdMuonRange range="LEX8" pedVal="6.2" pedSig="0.7" />
            <tholdMuonRange range="LEX1" pedVal="5.9" pedSig="0.5" />
            <tholdMuonRange range="HEX8" pedVal="8.2" pedSig="1.7" />
          </tholdMuon>
        </face>
        <face end="POS">
          <tholdMuon FLEVal="8.1" FLESig="0.5" FHEVal="14.2" FHESig="0.9">
<!-- Just leave out unused range -->
            <tholdMuonRange range="LEX8" pedVal="5.8" pedSig="0.6" />
            <tholdMuonRange range="LEX1" pedVal="6.3" pedSig="0.6" />
            <tholdMuonRange range="HEX8" pedVal="7.2" pedSig="0.6" />
          </tholdMuon>
        </face>
      </xtal>

<!-- on to next log -->
      <xtal iXtal="1">
         <face end="NEG">
           <tholdMuon FLEVal="7.0" FLESig="0.3" FHEVal="13.2" FHESig="0.7">
<!-- Just leave out unused range -->
             <tholdMuonRange range="LEX8" pedVal="6.1" pedSig="0.6" />
             <tholdMuonRange range="LEX1" pedVal="5.8" pedSig="0.4" />
             <tholdMuonRange range="HEX8" pedVal="8.1" pedSig="1.6" />
          </tholdMuon>
        </face>
        <face end="POS">
          <tholdMuon FLEVal="8.1" FLESig="0.5" FHEVal="14.2" FHESig="0.9">
<!-- Just leave out unused range -->
            <tholdMuonRange range="LEX8" pedVal="5.7" pedSig="0.5" />
            <tholdMuonRange range="LEX1" pedVal="6.2" pedSig="0.5" />
            <tholdMuonRange range="HEX8" pedVal="7.1" pedSig="0.5" />
          </tholdMuon>
        </face>
      </xtal>
    </layer>

<!-- 2nd layer (layer 1) -->
    <layer iLayer="1">
      <xtal iXtal="0">
        <face end="NEG">
          <tholdMuon FLEVal="8.0" FLESig="0.4" FHEVal="14.1" FHESig="0.8">
<!-- Just leave out unused range -->
            <tholdMuonRange range="LEX8" pedVal="6.2" pedSig="0.7" />
            <tholdMuonRange range="LEX1" pedVal="5.9" pedSig="0.5" />
            <tholdMuonRange range="HEX8" pedVal="8.2" pedSig="1.7" />
          </tholdMuon>
        </face>
        <face end="POS">
          <tholdMuon FLEVal="8.1" FLESig="0.5" FHEVal="14.2" FHESig="0.9">
<!-- Just leave out unused range -->
            <tholdMuonRange range="LEX8" pedVal="5.8" pedSig="0.6" />
            <tholdMuonRange range="LEX1" pedVal="6.3" pedSig="0.6" />
            <tholdMuonRange range="HEX8" pedVal="7.2" pedSig="0.6" />
          </tholdMuon>
        </face>
      </xtal>

<!-- on to next log -->
      <xtal iXtal="1">
         <face end="NEG">
           <tholdMuon FLEVal="7.0" FLESig="0.3" FHEVal="13.2" FHESig="0.7">
<!-- Just leave out unused range -->
             <tholdMuonRange range="LEX8" pedVal="6.1" pedSig="0.6" />
             <tholdMuonRange range="LEX1" pedVal="5.8" pedSig="0.4" />
             <tholdMuonRange range="HEX8" pedVal="8.1" pedSig="1.6" />
          </tholdMuon>
        </face>
        <face end="POS">
          <tholdMuon FLEVal="8.1" FLESig="0.5" FHEVal="14.2" FHESig="0.9">
<!-- Just leave out unused range -->
            <tholdMuonRange range="LEX8" pedVal="5.7" pedSig="0.5" />
            <tholdMuonRange range="LEX1" pedVal="6.2" pedSig="0.5" />
            <tholdMuonRange range="HEX8" pedVal="7.1" pedSig="0.5" />
          </tholdMuon>
        </face>
      </xtal>
    </layer>

<!-- 3rd layer (layer 2) -->
    <layer iLayer="2">
      <xtal iXtal="0">
        <face end="NEG">
          <tholdMuon FLEVal="8.0" FLESig="0.4" FHEVal="14.1" FHESig="0.8">
<!-- Just leave out unused range -->
            <tholdMuonRange range="LEX8" pedVal="6.2" pedSig="0.7" />
            <tholdMuonRange range="LEX1" pedVal="5.9" pedSig="0.5" />
            <tholdMuonRange range="HEX8" pedVal="8.2" pedSig="1.7" />
          </tholdMuon>
        </face>
        <face end="POS">
          <tholdMuon FLEVal="8.1" FLESig="0.5" FHEVal="14.2" FHESig="0.9">
<!-- Just leave out unused range -->
            <tholdMuonRange range="LEX8" pedVal="5.8" pedSig="0.6" />
            <tholdMuonRange range="LEX1" pedVal="6.3" pedSig="0.6" />
            <tholdMuonRange range="HEX8" pedVal="7.2" pedSig="0.6" />
          </tholdMuon>
        </face>
      </xtal>

<!-- on to next log -->
      <xtal iXtal="1">
         <face end="NEG">
           <tholdMuon FLEVal="7.0" FLESig="0.3" FHEVal="13.2" FHESig="0.7">
<!-- Just leave out unused range -->
             <tholdMuonRange range="LEX8" pedVal="6.1" pedSig="0.6" />
             <tholdMuonRange range="LEX1" pedVal="5.8" pedSig="0.4" />
             <tholdMuonRange range="HEX8" pedVal="8.1" pedSig="1.6" />
          </tholdMuon>
        </face>
        <face end="POS">
          <tholdMuon FLEVal="8.1" FLESig="0.5" FHEVal="14.2" FHESig="0.9">
<!-- Just leave out unused range -->
            <tholdMuonRange range="LEX8" pedVal="5.7" pedSig="0.5" />
            <tholdMuonRange range="LEX1" pedVal="6.2" pedSig="0.5" />
            <tholdMuonRange range="HEX8" pedVal="7.1" pedSig="0.5" />
          </tholdMuon>
        </face>
      </xtal>
    </layer>

  </tower>

</calCalib>
