=== fermi-lat/calibUtil/xml/acdCalib_v1r1.dtd
<!--
   $Header: /nfs/slac/g/glast/ground/cvs/calibUtil/xml/acdCalib_v0.dtd,v 1.1 2004/06/11 20:12:14 jrb Exp $

   /**  @file       acdCalib.dtd
        @authors    E. Charles

        dtd for ACD calibration data types

    */

 -->

<!-- 
   Overall structure is some header information followed by
   a sequence of tile (or ribbon) data.  Tile (or ribbon) data is made up
   of data form the 2 PMTs that read the tile

   The header information comes in two parts:
     "generic" is relevant to any sort of calibration data,
               not just that from the ACD, such as the
               name of the instrument being calibrated.
               See further comments above the generic element
               declaration
     "dimension" contains all the parameters necessary to figure 
               out which data goes with which hardware entity.
               See further comments above the dimension element
               declaration
  -->  

<!ELEMENT acdCalib (generic, dimension, tile* ) >
       
<!-- Container for all the header/metadata type information to be
     included here.  Complete metadata will be found in the calibration
     MySQL database. 

     Description of attributes:

            instrument    - one of "flight", "EM", etc.  Could also
                            be implemented as enumeration rather than
                            NMTOKEN
            timestamp     - when the file was written (date and time)
            calType       - one of "TKRBadStrips", "CALLightAttenuation",
                            etc.
            formatVersion - sufficient versioning information so that
                            software attempting to read the file can
                            determine if it supports this version. 
                            [Might get rid of this here and just keep
                            it in the MySQL metadata table]
 -->
<!ELEMENT  generic (inputSample?) >
<!ATTLIST generic  
   instrument  (LAT | CalUnit | MiniLat) #REQUIRED
   timestamp   CDATA #REQUIRED
   calibType ( ACD_Pedestal | ACD_Gain | ACD_Veto | ACD_Cno | ACD_HighRange ) #REQUIRED              
   algorithm   CDATA #REQUIRED
   DTDVersion  NMTOKEN "v0"       
   fmtVersion  NMTOKEN #REQUIRED>

<!-- Description of events used as input to the procedure 
     Start- and stop-times should be timestamps of earliest and
     latest events included in sample.
     inputSample is (for now) optional.
-->
<!ELEMENT inputSample (#PCDATA) >
<!ATTLIST inputSample  startTime CDATA #REQUIRED
                       stopTime  CDATA #REQUIRED
                       triggers  CDATA #REQUIRED 
                       source    CDATA #REQUIRED
                       mode      NMTOKEN  #REQUIRED>

<!-- Describe how the data is dimensioned:
        nTile:  number of tiles+ribbons and not-connected channels
                (no default; should be 108 for LAT)
        nFace:  face+ribbon orientations  (default = 5 + 2 = 7)
        nRow:   max number       (default = 5, occurs in top face)
        nCol:   max number       (default = 5, occurs in top face)
        nPmt:   number of PMT      (default = 2)
        nNA:    number of unconnected channels (default = 11)
        exact:  true if number of subelements = nTile*nPmt, else
                false.  Default is true.
 -->
  
<!ELEMENT dimension EMPTY>
<!ATTLIST dimension nTile NMTOKEN  #REQUIRED
                    nFace NMTOKEN  "7"
                    nRow  NMTOKEN  "5"
                    nCol  NMTOKEN  "5"
                    nPmt  NMTOKEN  "2"
                    nNA   NMTOKEN  "11"
                    exact NMTOKEN #FIXED "true"     >

<!ELEMENT tile (pmt,pmt) >
<!ATTLIST tile tileId NMTOKEN #REQUIRED>

<!ELEMENT pmt (acdPed* | acdGain* | acdVeto* | acdCno* | acdHighRange*) >
<!ATTLIST pmt iPmt NMTOKEN #REQUIRED>

<!ELEMENT acdPed  EMPTY>
<!ATTLIST acdPed  mean NMTOKEN #REQUIRED
                  width NMTOKEN #REQUIRED
                  status NMTOKEN #REQUIRED >

<!ELEMENT acdGain EMPTY>
<!ATTLIST acdGain peak NMTOKEN #REQUIRED
                  width NMTOKEN #REQUIRED
                  status NMTOKEN #REQUIRED >

<!ELEMENT acdVeto EMPTY>
<!ATTLIST acdVeto veto NMTOKEN #REQUIRED
                  width NMTOKEN #REQUIRED
                  status NMTOKEN #REQUIRED >

<!ELEMENT acdCno EMPTY>
<!ATTLIST acdCno cno NMTOKEN #REQUIRED
                 width NMTOKEN #REQUIRED
                 status NMTOKEN #REQUIRED >

<!ELEMENT acdHighRange EMPTY>
<!ATTLIST acdHighRange >
<!-- ATTLIST acdHighRange cno NMTOKEN #REQUIRED
                 width NMTOKEN #REQUIRED
                 status NMTOKEN #REQUIRED -->

=== fermi-lat/calibUtil/xml/Acd/acdPedTest.xml
<!DOCTYPE acdCalib SYSTEM "../acdCalib_v1r1.dtd" [] >
<acdCalib>
<generic instrument="LAT" timestamp="Tue Jan 31 10:49:15 2006" calibType="ACD_Pedestal" algorithm="Stats" fmtVersion="v1r1">
  <inputSample startTime="135005337:1" stopTime="135005341:103659" triggers="5974/312742" source="0" mode="0"/>
</generic>
<dimension nTile="108"/>
  <tile tileId="000">
    <pmt iPmt="0">
      <acdPed mean="206.039" width=" 3.0171" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="153.875" width=" 3.32973" status="0"/>
    </pmt>
  </tile>
  <tile tileId="001">
    <pmt iPmt="0">
      <acdPed mean="217.599" width=" 2.4545" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="167.039" width=" 2.99675" status="0"/>
    </pmt>
  </tile>
  <tile tileId="002">
    <pmt iPmt="0">
      <acdPed mean="182.576" width=" 2.87757" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="139.187" width=" 2.93128" status="0"/>
    </pmt>
  </tile>
  <tile tileId="003">
    <pmt iPmt="0">
      <acdPed mean="444.107" width=" 2.80754" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="553.386" width=" 2.86582" status="0"/>
    </pmt>
  </tile>
  <tile tileId="004">
    <pmt iPmt="0">
      <acdPed mean="200.951" width=" 2.65268" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="136.331" width=" 2.61026" status="0"/>
    </pmt>
  </tile>
  <tile tileId="010">
    <pmt iPmt="0">
      <acdPed mean="194.23" width=" 2.56516" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="727.965" width=" 3.81982" status="0"/>
    </pmt>
  </tile>
  <tile tileId="011">
    <pmt iPmt="0">
      <acdPed mean="136.663" width=" 2.68275" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="216.546" width=" 2.77578" status="0"/>
    </pmt>
  </tile>
  <tile tileId="012">
    <pmt iPmt="0">
      <acdPed mean="173.397" width=" 3.08126" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="366.031" width=" 3.45697" status="0"/>
    </pmt>
  </tile>
  <tile tileId="013">
    <pmt iPmt="0">
      <acdPed mean="198.513" width=" 3.17287" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="166.55" width=" 2.50492" status="0"/>
    </pmt>
  </tile>
  <tile tileId="014">
    <pmt iPmt="0">
      <acdPed mean="498.273" width=" 2.64894" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="391.415" width=" 2.53282" status="0"/>
    </pmt>
  </tile>
  <tile tileId="020">
    <pmt iPmt="0">
      <acdPed mean="444.034" width=" 2.92428" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="217.35" width=" 3.41396" status="0"/>
    </pmt>
  </tile>
  <tile tileId="021">
    <pmt iPmt="0">
      <acdPed mean="260.668" width=" 2.9054" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="511.658" width=" 3.04144" status="0"/>
    </pmt>
  </tile>
  <tile tileId="022">
    <pmt iPmt="0">
      <acdPed mean="492.018" width=" 2.83565" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="490.471" width=" 3.29021" status="0"/>
    </pmt>
  </tile>
  <tile tileId="023">
    <pmt iPmt="0">
      <acdPed mean="209.052" width=" 2.84001" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="151.314" width=" 2.73311" status="0"/>
    </pmt>
  </tile>
  <tile tileId="024">
    <pmt iPmt="0">
      <acdPed mean="120.917" width=" 2.92592" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="107.931" width=" 2.90045" status="0"/>
    </pmt>
  </tile>
  <tile tileId="030">
    <pmt iPmt="0">
      <acdPed mean="174.073" width=" 3.16692" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="137.25" width=" 2.61642" status="0"/>
    </pmt>
  </tile>
  <tile tileId="031">
    <pmt iPmt="0">
      <acdPed mean="598.168" width=" 2.66019" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="166.608" width=" 2.60391" status="0"/>
    </pmt>
  </tile>
  <tile tileId="032">
    <pmt iPmt="0">
      <acdPed mean="195.605" width=" 2.66916" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="685.511" width=" 4.36918" status="0"/>
    </pmt>
  </tile>
  <tile tileId="033">
    <pmt iPmt="0">
      <acdPed mean="146.645" width=" 2.69918" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="204.744" width=" 2.88997" status="0"/>
    </pmt>
  </tile>
  <tile tileId="034">
    <pmt iPmt="0">
      <acdPed mean="201.783" width=" 2.67773" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="617.644" width=" 3.06182" status="0"/>
    </pmt>
  </tile>
  <tile tileId="040">
    <pmt iPmt="0">
      <acdPed mean="337.948" width=" 2.79555" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="281.833" width=" 2.92665" status="0"/>
    </pmt>
  </tile>
  <tile tileId="041">
    <pmt iPmt="0">
      <acdPed mean="204.25" width=" 2.83148" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="567.51" width=" 2.45106" status="0"/>
    </pmt>
  </tile>
  <tile tileId="042">
    <pmt iPmt="0">
      <acdPed mean="141.788" width=" 2.69631" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="413.845" width=" 3.30394" status="0"/>
    </pmt>
  </tile>
  <tile tileId="043">
    <pmt iPmt="0">
      <acdPed mean="227.681" width=" 3.31589" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="633.424" width=" 2.57775" status="0"/>
    </pmt>
  </tile>
  <tile tileId="044">
    <pmt iPmt="0">
      <acdPed mean="233.391" width=" 3.31424" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="532.299" width=" 3.06753" status="0"/>
    </pmt>
  </tile>
  <tile tileId="100">
    <pmt iPmt="0">
      <acdPed mean="154.509" width=" 3.16866" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="437.901" width=" 2.52191" status="0"/>
    </pmt>
  </tile>
  <tile tileId="101">
    <pmt iPmt="0">
      <acdPed mean="223.253" width=" 2.78595" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="147.856" width=" 2.69401" status="0"/>
    </pmt>
  </tile>
  <tile tileId="102">
    <pmt iPmt="0">
      <acdPed mean="273.422" width=" 2.6572" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="124.887" width=" 2.94017" status="0"/>
    </pmt>
  </tile>
  <tile tileId="103">
    <pmt iPmt="0">
      <acdPed mean="144.045" width=" 3.82799" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="247.396" width=" 3.0786" status="0"/>
    </pmt>
  </tile>
  <tile tileId="104">
    <pmt iPmt="0">
      <acdPed mean="542.407" width=" 2.9477" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="128.968" width=" 2.77263" status="0"/>
    </pmt>
  </tile>
  <tile tileId="110">
    <pmt iPmt="0">
      <acdPed mean="181.892" width=" 2.25762" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="253.667" width=" 3.40997" status="0"/>
    </pmt>
  </tile>
  <tile tileId="111">
    <pmt iPmt="0">
      <acdPed mean="184.652" width=" 3.36619" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="243.768" width=" 3.19509" status="0"/>
    </pmt>
  </tile>
  <tile tileId="112">
    <pmt iPmt="0">
      <acdPed mean="420.069" width=" 2.89667" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="375.298" width=" 2.97411" status="0"/>
    </pmt>
  </tile>
  <tile tileId="113">
    <pmt iPmt="0">
      <acdPed mean="449.185" width=" 3.73369" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="353.824" width=" 2.66339" status="0"/>
    </pmt>
  </tile>
  <tile tileId="114">
    <pmt iPmt="0">
      <acdPed mean="300.482" width=" 2.69402" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="178.298" width=" 2.49262" status="0"/>
    </pmt>
  </tile>
  <tile tileId="120">
    <pmt iPmt="0">
      <acdPed mean="243.969" width=" 2.64006" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="328.654" width=" 3.02315" status="0"/>
    </pmt>
  </tile>
  <tile tileId="121">
    <pmt iPmt="0">
      <acdPed mean="287.331" width=" 2.64935" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="513.115" width=" 3.96467" status="0"/>
    </pmt>
  </tile>
  <tile tileId="122">
    <pmt iPmt="0">
      <acdPed mean="107.037" width=" 2.89654" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="615.412" width=" 2.72886" status="0"/>
    </pmt>
  </tile>
  <tile tileId="123">
    <pmt iPmt="0">
      <acdPed mean="220.529" width=" 2.62363" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="195.213" width=" 2.77438" status="0"/>
    </pmt>
  </tile>
  <tile tileId="124">
    <pmt iPmt="0">
      <acdPed mean="140.19" width=" 3.0053" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="452.832" width=" 3.19109" status="0"/>
    </pmt>
  </tile>
  <tile tileId="130">
    <pmt iPmt="0">
      <acdPed mean="140.579" width=" 2.6619" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="194.709" width=" 2.56811" status="0"/>
    </pmt>
  </tile>
  <tile tileId="200">
    <pmt iPmt="0">
      <acdPed mean="146.456" width=" 2.66036" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="163.983" width=" 2.57817" status="0"/>
    </pmt>
  </tile>
  <tile tileId="201">
    <pmt iPmt="0">
      <acdPed mean="193.277" width=" 3.17121" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="377.589" width=" 2.61963" status="0"/>
    </pmt>
  </tile>
  <tile tileId="202">
    <pmt iPmt="0">
      <acdPed mean="172.609" width=" 3.27391" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="117.484" width=" 2.93683" status="0"/>
    </pmt>
  </tile>
  <tile tileId="203">
    <pmt iPmt="0">
      <acdPed mean="201.783" width=" 2.47569" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="465.505" width=" 3.01453" status="0"/>
    </pmt>
  </tile>
  <tile tileId="204">
    <pmt iPmt="0">
      <acdPed mean="651.393" width=" 2.61755" status="0"/>
    </pmt>
    <pmt iPmt="1">
      <acdPed mean="404.903" width=" 2.81146" status="0"/>
    </pmt>
  </tile>
