=== fermi-lat/calibUtil/xml/calCalib_v1.dtd
<!--
   $Header: $

   /**  @file       calCalib.dtd
        @authors    J. Bogart

        dtd for CAL calibration data types

    */

 -->

<!-- 
   Overall structure is some header information followed by
   a sequence of elements of the same type (such as calPed),
   each of which contains the information belonging to a single
   range of a single crystal (of a single face, where appropriate).

   The header information comes in two parts:
     "generic" is relevant to any sort of calibration data,
               not just that from the CAL, such as the
               name of the instrument being calibrated.
               See further comments above the generic element
               declaration
     "dimension" contains all the parameters necessary to figure 
               out which data goes with which hardware entity.
               See further comments above the dimension element
               declaration
  -->  

<!ELEMENT calCalib (generic, dimension, (calPed* | calGain*)) >


       
<!-- Container for all the header/metadata type information to be
     included here.  Complete metadata will be found in the calibration
     MySQL database. 

     Description of attributes:

            instrument    - one of "flight", "EM", etc.  Could also
                            be implemented as enumeration rather than
                            NMTOKEN
            timestamp     - when the file was written (date and time)
            calType       - one of "TKRBadStrips", "CALLightAttenuation",
                            etc.
            formatVersion - sufficient versioning information so that
                            software attempting to read the file can
                            determine if it supports this version. 
                            [Might get rid of this here and just keep
                            it in the MySQL metadata table]
 -->
<!ELEMENT  generic  (inputSample?) >
<!ATTLIST generic  
   instrument  (LAT | BFEM | BTEM | EM | CU) #REQUIRED
   timestamp   NMTOKEN #REQUIRED
   calibType (CAL_LightAtt | CAL_LightAsym | CAL_LightYield |
              CAL_Ped | CAL_ElecGain | CAL_IntNonlin | CALDiffNonlin |
              CAL_DiscrLO | CAL_DiscrHI )    #REQUIRED
   DTDVersion  NMTOKEN "v1r0"       
   fmtVersion  NMTOKEN #REQUIRED >

<!-- Description of events used as input to the procedure 
     Start- and stop-times should be timestamps of earliest and
     latest events included in sample.
     inputSample is (for now) optional.
-->
<!ELEMENT inputSample (#PCDATA) >
<!ATTLIST inputSample  startTime NMTOKEN #REQUIRED
                       stopTime  NMTOKEN #REQUIRED
                       triggers  NMTOKENS #REQUIRED 
                       source    NMTOKENS #REQUIRED
                       mode      NMTOKEN  #REQUIRED>

<!-- Describe how the data is dimensioned:
        number of tower rows
        number of tower columns
        number of calorimeter layers
        number of crystals in a layer ("columns")
        number of faces      (mostly 2; 1 for light asymmetry data)
        number of ranges     (fixed at 4? for now just default to 4) 
   Use the following conventions to determine which data element 
   corresponds to a particular physical crystal, optional face and
   gain range:
       * Tower number is computed from row and column as
                 tower = column + (nCol)*row
       * The data can be viewed as a 5-dimensional array where
         the indices from most- to least-significant are
              tower
              layer
              xtal   (often called "column" in calorimeter code)
              face
              range
         So the first two data elements will correspond to 
           (tower=0,layer=0, xtal=0, face=0, range=0)
           (tower=0,layer=0, xtal=0, face=0, range=1)
 
         The total number of data elements is just
                nRow*nCol*nLayer*nXtal*nFace*nRange

 -->
<!ELEMENT dimension EMPTY>
<!ATTLIST dimension nRow NMTOKEN  #REQUIRED
                    nCol NMTOKEN  #REQUIRED
                    nLayer NMTOKEN #REQUIRED
                    nXtal  NMTOKEN #REQUIRED
                    nFace  NMTOKEN #REQUIRED
                    nRange NMTOKEN "4"       >

<!ELEMENT calPed  EMPTY>
<!ATTLIST calPed  avg NMTOKEN #REQUIRED
                  sig NMTOKEN #REQUIRED>

<!ELEMENT calGain EMPTY>
<!ATTLIST calGain gain NMTOKEN #REQUIRED>

=== fermi-lat/calibUtil/xml/test/testCalPed_v1.xml
<?xml version="1.0" ?>

<!-- $Header: $ -->

<!-- mini test CAL ped  XML file according to calCalib.dtd -->

<!DOCTYPE calCalib SYSTEM "../calCalib_v1.dtd" [] >

<calCalib>
  <generic instrument="LAT" timestamp="2002-11-2-12:56" 
           calibType="CAL_Ped" fmtVersion="v1r0">

    <inputSample startTime="2002-1-1-00:00" stopTime="2002-6-1-00:00" 
                 triggers="random" mode="normal" source="stuff" >
     There is no input sample in fact.
     Everything is just made up for code testing.
     Note the entire inputSample element is optional.  It could
     be omitted altogether.
    </inputSample>
  </generic>


<!-- The dimensions here correspond to no real instrument, of course.
     I made them small for purposes of illustration.  With these
     dimensions, the total number of calPed elements to follow should
     be 1*1*2*4*2*4 = 64,  but I haven't included them all.
  -->
 
  <dimension nRow="1" nCol="1" nLayer="2" nXtal="4" nFace="2" />  

  <!-- Data for layer 0, xtal 0, face 0 -->
  <calPed avg="8" sig="0.4" />
  <calPed avg="8" sig="0.3" />
  <calPed avg="6" sig="0.4" />
  <calPed avg="7" sig="0.4" />
  
  <!-- Data for layer 0, xtal 0, face 1 -->
  <calPed avg="7" sig="0.6" />
  <calPed avg="8" sig="0.3" />
  <calPed avg="6" sig="0.7" />
  <calPed avg="7" sig="0.4" />

  <!-- Data for layer 0, xtal 1 -->
  <calPed avg="8" sig="0.4" />  
  <calPed avg="8" sig="0.4" />  
  <calPed avg="8" sig="0.4" />  
  <calPed avg="8" sig="0.4" />  
  <calPed avg="8" sig="0.4" />  
  <calPed avg="8" sig="0.4" />  
  <calPed avg="8" sig="0.4" />  
  <calPed avg="8" sig="0.4" />

<!-- A legitimate file consistent with the values in the dimension element
     above would have 8 more calPed elements following each of the 
     comment lines below -->
  <!-- Data for layer 0, xtal 2 -->

  <!-- Data for layer 0, xtal 3 -->


  <!-- Data for layer 1, xtal 0 -->

  <!-- Data for layer 1, xtal 1 -->

  <!-- Data for layer 1, xtal 2 -->

  <!-- Data for layer 1, xtal 3 -->

</calCalib>
