=== fermi-lat/calibUtil/xml/calCalib_v2r1.dtd
<!--
   $Header: /nfs/slac/g/glast/ground/cvs/calibUtil/xml/calCalib_v2r1.dtd,v 1.1 2004/05/20 23:32:30 jrb Exp $

   /**  @file       calCalib.dtd
        @authors    J. Bogart

        dtd for CAL calibration data types

    */

 -->

<!-- 
   Overall structure is some header information followed by
   a sequence of tower data.  Tower data is made up
   of layer data, in turn made up of data for individual
   crystals, which consists of data for (1 or 2, depending
   on calibration type) faces.  

   The header information comes in two parts:
     "generic" is relevant to any sort of calibration data,
               not just that from the CAL, such as the
               name of the instrument being calibrated.
               See further comments above the generic element
               declaration
     "dimension" contains all the parameters necessary to figure 
               out which data goes with which hardware entity.
               See further comments above the dimension element
               declaration
  -->  

<!ELEMENT calCalib (generic, dimension, dac*, tower* ) >
       
<!-- Container for all the header/metadata type information to be
     included here.  Complete metadata will be found in the calibration
     MySQL database. 

     Description of attributes:

            instrument    - one of "flight", "EM", etc.  Could also
                            be implemented as enumeration rather than
                            NMTOKEN
            timestamp     - when the file was written (date and time)
            calType       - one of "TKRBadStrips", "CALLightAttenuation",
                            etc.
            formatVersion - sufficient versioning information so that
                            software attempting to read the file can
                            determine if it supports this version. 
                            [Might get rid of this here and just keep
                            it in the MySQL metadata table]
 -->
<!ELEMENT  generic  (inputSample?) >
<!ATTLIST generic  
   instrument  (LAT | BFEM | BTEM | EM | EM2 | CU) #REQUIRED
   timestamp   NMTOKEN #REQUIRED
   calibType (CAL_LightAtt | CAL_LightAsym | CAL_LightYield |
              CAL_Ped | CAL_ElecGain | CAL_IntNonlin | CALDiffNonlin |
              CAL_DiscrLO | CAL_DiscrHI | CAL_MuSlope)    #REQUIRED
   DTDVersion  NMTOKEN "v2r0"       
   fmtVersion  NMTOKEN #REQUIRED >

<!-- Description of events used as input to the procedure 
     Start- and stop-times should be timestamps of earliest and
     latest events included in sample.
     inputSample is (for now) optional.
-->
<!ELEMENT inputSample (#PCDATA) >
<!ATTLIST inputSample  startTime NMTOKEN #REQUIRED
                       stopTime  NMTOKEN #REQUIRED
                       triggers  NMTOKENS #REQUIRED 
                       source    NMTOKENS #REQUIRED
                       mode      NMTOKEN  #REQUIRED>

<!-- In many cases calibration is done per range: LEX8 is low-energy 
   (= large) diode, x8 amplification; LEX1 is low-energy, low amplification.
   Similarly have HEX8, HEX1 for high-energy (small) diode  -->
<!ENTITY  % ranges  'range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED ' >

<!-- For light asymmetry may lump together amplifications (and by
  definition one set of constants applies to both crystal ends, since
  constants quantify *asymmetry*), so have a set of constants per
  diode-type -->
<!ENTITY  % diodes  'diode (LE | HE) #REQUIRED ' >

<!-- Describe how the data is dimensioned:
        number of tower rows
        number of tower columns
        number of calorimeter layers
        number of crystals in a layer ("columns")
        number of faces      (mostly 2; 1 for light asymmetry data)
        number of ranges     (fixed at 4? for now just default to 4) 
        number of sets of dac settings (mostly 0)
        exact    may be "true" or "false".  If "true", above information
                 may be mutliplied to compute total number of innermost
                 elements (e.g., calPed)

   Use the following conventions to determine which data element 
   corresponds to a particular physical crystal, optional face and
   gain range:
       * Tower number is computed from row and column as
                 tower = column + (nCol)*row
       * The data can be viewed as a 5-dimensional array where
         the indices from most- to least-significant are
              tower
              layer
              xtal   (often called "column" in calorimeter code)
              face
              range
         So the first two data elements will correspond to 
           (tower=0,layer=0, xtal=0, face=0, range=0)
           (tower=0,layer=0, xtal=0, face=0, range=1)
 
         The total number of data elements (for the default
         case, with exact = "true") is just
                nRow*nCol*nLayer*nXtal*nFace*nRange

 -->
<!ELEMENT dimension EMPTY>
<!ATTLIST dimension nRow NMTOKEN  #REQUIRED
                    nCol NMTOKEN  #REQUIRED
                    nLayer NMTOKEN #REQUIRED
                    nXtal  NMTOKEN #REQUIRED
                    nFace  NMTOKEN #REQUIRED
                    nRange NMTOKEN "4"      
                    nDacCol NMTOKEN "0" 
                    exact  (true | false) "true" >

<!-- For those calibrations involving setting a dac, keep track of
    settings.  Expect one set per range where used; else 0. Number 
    should match value of dimension attribute nDacCol  -->
<!ELEMENT dac EMPTY>
<!ATTLIST dac %ranges;
          values NMTOKENS #REQUIRED >

<!ELEMENT tower (layer*) >
<!ATTLIST tower iRow NMTOKEN #REQUIRED
                iCol NMTOKEN #REQUIRED >

<!ELEMENT layer (xtal*) >
<!ATTLIST layer iLayer NMTOKEN #REQUIRED>

<!ELEMENT xtal (face, face?) >
<!ATTLIST xtal iXtal NMTOKEN #REQUIRED>

<!-- each face has data for all four ranges, ordered by range number -->
<!ELEMENT face (calPed* | calGain* | muSlope* | lightAsym* | intNonlin* ) >
<!ATTLIST face end (NEG | POS | NA) #REQUIRED >


<!ELEMENT calPed  EMPTY>
<!ATTLIST calPed  %ranges;
                  avg NMTOKEN #REQUIRED
                  sig NMTOKEN #REQUIRED
                  cos NMTOKEN "2" >

<!ELEMENT calGain EMPTY>
<!ATTLIST calGain %ranges;
                  avg NMTOKEN #REQUIRED
                  sig NMTOKEN #REQUIRED>

<!ELEMENT muSlope EMPTY>
<!ATTLIST muSlope %ranges;
                  slope NMTOKEN #REQUIRED
                  error NMTOKEN "0.0" >

<!ELEMENT lightAsym EMPTY>
<!ATTLIST lightAsym %diodes;
                    values NMTOKENS #REQUIRED
                    error NMTOKEN #REQUIRED >

<!ELEMENT intNonlin EMPTY>
<!ATTLIST intNonlin %ranges;
                    values NMTOKENS #REQUIRED
                    error NMTOKEN   #REQUIRED >

=== fermi-lat/calibUtil/xml/Cal/CalLightAsym_EM1_test.xml
<?xml version="1.0" ?>
<!-- $Header: $  -->
<!-- Made-up  light atten XML file for EM, according to calCalib_v2-new.dtd -->

<!DOCTYPE calCalib SYSTEM "../calCalib_v2r1.dtd" [] >

<calCalib>
  <generic instrument="EM" timestamp="2003-11-2-12:56"
           calibType="CAL_LightAsym" fmtVersion="v2r0">

    <inputSample startTime="2003-2-21-05:49:12" stopTime="2003-2-24-07:07:02"
		triggers="random" mode="normal" source="stuff" >

		Times are start and stop time of calibration run.
		Other attributes are just made up for code testing.
    </inputSample>
  </generic>


  <!-- EM instrument: 8 layers, 12 columns -->

  <dimension nRow="1" nCol="1" nLayer="8" nXtal="12" nFace="1" nRange="2"/>

  <tower iRow="0" iCol="0">
    <layer iLayer="0">
      <xtal iXtal="0">
	<face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="1">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />

        </face>
      </xtal>
      <xtal iXtal="2">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="3">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="4">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="5">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="6">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="7">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="8">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="9">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="10">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="11">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
    </layer>
    <layer iLayer="1">
      <xtal iXtal="0">
	<face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="1">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />

        </face>
      </xtal>
      <xtal iXtal="2">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="3">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="4">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="5">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="6">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="7">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="8">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="9">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="10">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="11">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
    </layer>

    <layer iLayer="2">
      <xtal iXtal="0">
	<face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="1">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />

        </face>
      </xtal>
      <xtal iXtal="2">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
        </face>
      </xtal>
      <xtal iXtal="3">
        <face end="NA">
          <lightAsym diode="LE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
          <lightAsym diode="HE"
               values="0.1 1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9 9.0"
               error="0.1" />
