<?xml version="1.0" ?>
<!DOCTYPE ancCalib [
<!--
   $Header: $

   /**  @file       ancillaryCalib.dtd
        @authors    J. Bogart

        dtd for ancillary calibration data types
    */
 -->
<!-- 
   Overall structure is some header information followed by
   a sequence of module data.  Module data is made up
   of layer data, in turn made up of data for channels.

   The header information comes in two parts:
     "generic" is relevant to any sort of calibration data,
               not just that from the CAL, such as the
               name of the instrument being calibrated.
               See further comments above the generic element
               declaration
     "dimension" contains all the parameters necessary to figure 
               out which data goes with which hardware entity.
               See further comments above the dimension element
               declaration
  -->  

<!ELEMENT ancCalib (generic, dimension, ancChan* ) >
       
<!-- Container for all the header/metadata type information to be
     included here.  Complete metadata will be found in the calibration
     MySQL database. 

     Description of attributes:

            instrument    - one of "flight", "EM", etc.  Could also
                            be implemented as enumeration rather than
                            NMTOKEN
            timestamp     - when the file was written (date and time)
            calibType       - one of "ANC_Ped" or ANC_Gain
            fmtVersion - sufficient versioning information so that
                            software attempting to read the file can
                            determine if it supports this version. 
                            [Might get rid of this here and just keep
                            it in the MySQL metadata table]
            creator       - script or program creating calibration data
 -->
<!ELEMENT  generic  EMPTY >
<!ATTLIST generic  
   instrument  (LAT | BFEM | BTEM | EM | EM2 | CU) #REQUIRED
   timestamp   CDATA #REQUIRED
   calibType (ANC_Ped | ANC_Gain)   #REQUIRED
   DTDVersion  NMTOKEN "v1r0"       
   fmtVersion  NMTOKEN #REQUIRED
   creator     CDATA #IMPLIED >

<!-- Describe how the data is dimensioned:
        number of modules
        number of layers per module
        number of channels per layer
        exact    may be "true" or "false".  If "true", above information
                 may be mutliplied to compute total number of innermost
                 elements (e.g., ancPed)
 -->
<!ELEMENT dimension EMPTY>
<!ATTLIST dimension nModule NMTOKEN  #REQUIRED
                    nLayer NMTOKEN #REQUIRED
                    nChannel NMTOKEN #REQUIRED
                    exact  (true | false) "true" >

<!ELEMENT ancChan (ancPed | ancGain) >
<!ATTLIST ancChan    iMod NMTOKEN #REQUIRED
                     iLay NMTOKEN #REQUIRED
                     iChan NMTOKEN #REQUIRED >


<!ELEMENT ancPed  EMPTY>
<!ATTLIST ancPed  ped NMTOKEN #REQUIRED
                  rNoise NMTOKEN #REQUIRED
                  sNoise NMTOKEN #REQUIRED
                  isBad  (0 | 1) "0" > 

<!ELEMENT ancGain EMPTY>
<!ATTLIST ancGain gain NMTOKEN #REQUIRED
                  isBad   (0 | 1) "0" > 
]>

<ancCalib>

  <generic  instrument="CU" timestamp="2006-06-07 23:12"
            calibType="ANC_Ped" fmtVersion="v1r0" creator="jrb" />
  <dimension nModule="1" nLayer="2" nChannel="4" />

  <ancChan iMod="0" iLay="0" iChan="0">
    <ancPed ped="155.891" rNoise="1.11046" sNoise="1.11046" />
  </ancChan>
  <ancChan iMod="0" iLay="0" iChan="1">
    <ancPed ped="142.053" rNoise="2.4654" sNoise="2.4654" />
  </ancChan>
  <ancChan iMod="0" iLay="0" iChan="2">
    <ancPed ped="153.165" rNoise="2.49775" sNoise="2.49775" />
  </ancChan>
  <ancChan iMod="0" iLay="0" iChan="3">
    <ancPed ped="180.226" rNoise="2.63226" sNoise="2.63226" />
  </ancChan>

  <ancChan iMod="0" iLay="1" iChan="0">
    <ancPed ped="155.029" rNoise="2.65464" sNoise="2.65464" />
  </ancChan>
  <ancChan iMod="0" iLay="1" iChan="1">
    <ancPed ped="155.887" rNoise="2.26468" sNoise="2.26468" />
  </ancChan>
  <ancChan iMod="0" iLay="1" iChan="2">
    <ancPed ped="154.177" rNoise="2.22848" sNoise="2.22848" />
  </ancChan>
  <ancChan iMod="0" iLay="1" iChan="3">
    <ancPed ped="163186" rNoise="2.15975" sNoise="2.15975" />
  </ancChan>
</ancCalib>
