<?xml version="1.0" ?>
<!DOCTYPE qdcCalib [
<!--
   $Header: /nfs/slac/g/glast/ground/cvs/calibUtil/xml/test/qdcExample.xml,v 1.1 2006/06/22 06:16:29 jrb Exp $

   /**  @file       qdcCalib.dtd
        @authors    J. Bogart

        dtd for qdc (ancillary channels other than tagger)
         calibration data types
    */
 -->

<!-- 
   Overall structure is some header information followed by
   a sequence of module data.  Module data is made up
   of layer data, in turn made up of data for channels.

   The header information comes in two parts:
     "generic" is relevant to any sort of calibration data,
               such as the name of the instrument (LAT or
               LAT-like prototype) whose data will be analyzed
               in the jobs using this calibration.

               See further comments above the generic element
               declaration
     "dimension" contains all the parameters necessary to figure 
               out which data goes with which hardware entity.
               See further comments above the dimension element
               declaration
  -->  
<!ELEMENT qdcCalib (generic, dimension, qdcChan*) >

<!-- Container for all the header/metadata type information to be
     included here.  Complete metadata will be found in the calibration
     MySQL database. 

     Description of attributes:

            instrument    - one of "flight", "EM", etc.  Could also
                            be implemented as enumeration rather than
                            NMTOKEN
            timestamp     - when the file was written (date and time)
            calibType     - QDC_pedgain
            fmtVersion    - sufficient versioning information so that
                            software attempting to read the file can
                            determine if it supports this version. 
            creator       - script or program creating calibration data
 -->
<!ELEMENT  generic  EMPTY >
<!ATTLIST generic  
   instrument  (LAT | BFEM | BTEM | EM | EM2 | CU) #REQUIRED
   timestamp   CDATA #REQUIRED
   calibType   NMTOKEN "QDC_ped"
   DTDVersion  NMTOKEN "v1r0"       
   fmtVersion  NMTOKEN #REQUIRED
   creator     CDATA #IMPLIED >

<!-- The calibration file describes one or more qdc modules
     each consisting of a number of channels.  
-->
<!-- Describe how the data is dimensioned:
        number of modules (max; may be larger than actual)
        number of channels per module  (max; may be larger than actual)
 -->
<!ELEMENT dimension EMPTY>
<!ATTLIST dimension nModule NMTOKEN  #REQUIRED
                    nChannel NMTOKEN #REQUIRED >


<!--  value for 'device' attribute can be any string at all, e.g.
           device="cerenkov channel 1"
 -->
<!ELEMENT qdcChan (qdcPed) >
<!ATTLIST qdcChan  iMod NMTOKEN #REQUIRED
                   iChan NMTOKEN #REQUIRED 
                   device CDATA " "
>

<!ELEMENT qdcPed  EMPTY>
<!ATTLIST qdcPed  ped NMTOKEN #REQUIRED
                  pedRms NMTOKEN #REQUIRED
                  isBad  NMTOKEN "0" > 
]>

<qdcCalib>
  <generic instrument="CU" timestamp="2005-06-21 20:57"
           calibType="QDC_ped"
           fmtVersion="v1r0"
           creator="jrb"
  />
  <dimension nModule="2" nChannel="32" />
  <qdcChan iMod="0" iChan="0" device="cerenkov_0">
    <qdcPed ped="23.2" pedRms="1.3" isBad="0" />
  </qdcChan>

  <qdcChan iMod="0" iChan="1" device="cerenkov_1">
    <qdcPed ped="27.1" pedRms="1.2" isBad="0" />
  </qdcChan>

<!-- would normally have several more channels for module 0,
     but no more than 32 total -->

   <qdcChan iMod="1"  iChan="0" device="trd_0">
    <qdcPed ped="19.1" pedRms="0.2" isBad="0" />
   </qdcChan>

   <!-- don't have to specify device -->
   <qdcChan iMod="1" iChan="1">
     <qdcPed ped="16.3" pedRms="2.1" isBad="0" />
   </qdcChan>

<!-- A real calibration file would have more channels for module 1 here -->
</qdcCalib>
